# Build from locally available container
FROM eclipse-cyclonedds-python-docker-base

# Make sure the contents of our repo are in ${HOME}
COPY --chown=${NB_USER} . ${HOME}

RUN python3 -m pip install --user --upgrade --no-cache-dir ./questing_package
